### ISSUE TITLE
Doors dont appear to open

### ISSUE THREAD

**Issue by haXs** [Automat-GH/minecrift#1]
Thanks for taking the time to make and release this fork for the Vive, Minecraft and room scale is just mind blowing. 

I have an issue where I can't interact with doors, the sound plays but the door does not open.
 I don't know if this is also the case in the base minecrift version.

**Comment by Automat-GH** [comment]
Are you playing singleplayer? Using teleport or sliding movement? Does the problem still happen if you're nearer the door?

**Comment by gazpachoking** [comment]
I had this problem as well, but it seemed to be just graphical. The door would open, and the hitbox would move, but the graphics were not updated, and the door still looked closed. You could move through it though, and if you aim at where the open door would be, you could close it.

**Comment by haXs** [comment]
I was in single player, It did not seem to matter how close to the door i was, i got right up to it, I was not able to move through it ( I was using teleport movement )

**Comment by neuhaus** [comment]
Are you teleporting onto the door trigger floor plate?

**Comment by haXs** [comment]
I have done some more testing and i realized that out of the box this works without issue, the problem comes if you then start to add mods into the mix, when i reported this i was running FTB Infinity 1.7.10 and for some reason the doors don't work

**Comment by Automat-GH** [comment]
Sounds like that mod changes the door or interaction code. Is the FTB source code available anywhere?
