### ISSUE TITLE
Can't compile installer

### ISSUE THREAD

**Issue by neuhaus** [Automat-GH/minecrift#2]
Thanks for the mod - I can't wait to try it.
Also thanks for enabling issues on this fork.

I tried to compile the installer using JDK1.8.0_92 64bit on Windows 10 Pro.
There are some failed patches and it reports "!! Modified jar detected. Unpredictable results !!"
The EXE file does not get built.
I'm attaching a [buildlog.txt](https://github.com/Automat-GH/minecrift/files/264595/buildlog.txt).

Is there reason why you're not providing an executable file?

**Comment by Automat-GH** [comment]
The false patch error messages and the modified jar message are expected. 

Try running build.bat after running install.bat.

**Comment by neuhaus** [comment]
OK, I ran `build.bat` after running `install.bat` but it fails.
Here is the log: [buildlog2.txt](https://github.com/Automat-GH/minecrift/files/265026/buildlog2.txt)

Looks like for some reason "javac" isn't in the path.. investigating.

**Comment by joshburt** [comment]
This does compile on the platform you are using, so this seems like an issue specific to you.

Ideas 
Can you confirm the python version you are using?
Can you confirm that the correct Java version is being using (you will most likely have several installed).

Since this is a fork, are you able to get the up stream repo to build?  (It should as well)

**Comment by neuhaus** [comment]
I solved it, I had installed both JRE 1.8.91 and JDK 1.8.92 and while JAVA_HOME pointed to the JDK the path pointed to C:\ProgramData\Oracle\java\javapath or something like that which contained symlinks to the **JRE** not the **JDK** so `javac` wasn't in the path.

I removed the JRE and fixed the path and now it builds!

**Comment by joshburt** [comment]
Enjoy it, it's an awesome experience :)
