### ISSUE TITLE
Audio not played via HTC Vive

### ISSUE THREAD

**Issue by neuhaus** [Automat-GH/minecrift#3]
when I launch Minecrift, the audio is routed via the normal speakers, not the HTC Vive.
When Minecraft is active, the default audio device is the HTC Vive.

**Comment by gazpachoking** [comment]
I think this would be to do with your windows/steamvr audio settings rather than a minecrift thing.

**Comment by neuhaus** [comment]
Other SteamVR titles open the little SteamVR status window while running and use the audio settings configured in SteamVR, Minecrift does not.

**Comment by joshburt** [comment]
I haven't been able to reproduce this (yet).  I do see the default playable device change occasionally outside of games, but switching it back to the vive and relaunching has resolved it the past.

**Comment by neuhaus** [comment]
In fact I have SteamVR configured to use both the Vive and the speakers while using the Vive and only the speakers when no longer using it.
It would be ideal if Minecrift were to honour this configuration like the other SteamVR titles do.

**Comment by Automat-GH** [comment]
You should be able to run SteamVR and see the status window independently of Minecrift. SteamVR can be configured to change your default audio device when it starts, then Minecrift should use that.

**Comment by neuhaus** [comment]
I can test this in more detail when I get back from a trip this weekend.
