### ISSUE TITLE
trying to launch the installer profile fails to download files

### ISSUE THREAD

**Issue by Too-DAMN-Much** [Automat-GH/minecrift#6]

**Comment by Too-DAMN-Much** [comment]
http://paste.ubuntu.com/16499442/

**Comment by haXs** [comment]
Can you walk through the steps you took to get this error? I can't replicate it myself

**Comment by Too-DAMN-Much** [comment]
that was trying to install over the top of an existing profile, a fresh one worked fine.

**Comment by haXs** [comment]
There should be a close button at the bottom , might be worth closing this off if you have fixed it
