### ISSUE TITLE
Using traditional motion could be more intuitive quite easily? (Hopefully)

### ISSUE THREAD

**Issue by Croccy22** [Automat-GH/minecrift#7]
For those of us who prefer the Traditional movement rather then teleport. Could you make it so the direction of movement is determined by the forward direction of the Left motion controller?

This would mean when you walk up to a wall for example, you can just point the controller behind you and pull the trigger to walk backwards.

Using this method would then also un-couple the head from movement. So you could walk in a straight line but have the ability to look around you while walking. I used this form of movement all the time on the DK2 version of minecrift and it works really well.

There is also a reddit post with people requesting the same thing (https://www.reddit.com/r/Vive/comments/4f3s0v/how_can_i_contact_the_minecraft_mod_dev_about_the/)

As with everything else it would be good to have this as an option so people who don't like it can keep it the way it is currently. But I personally think this would be a much better method.

Also the ability to walk fast/slow depending on how much you pull the trigger would also be another great option.

Thanks for your work on this so far. It's amazing!!!

**Comment by Too-DAMN-Much** [comment]
personally i'd like to be able to walk by using one of the thumbpads would be nice.

**Comment by kylebeee** [comment]
This^ i want to be able to move the direction i want while still viewing the thing im building

**Comment by Croccy22** [comment]
Someone has already done it :). https://github.com/jrbudda/minecrift/releases

**Comment by kylebeee** [comment]
That's awesome! I haven't been able to get it working for me what so ever though. I think i need someone to show me what to press to get it into the correct mode, I'm obviously missing something here. right Ctrl+R is not doing anything for me.

**Comment by jrbudda** [comment]
In my more current releases hold down the right grip button for 4 seconds to toggle into free move mode and it now defaults to left controller directed motion.

**Comment by Croccy22** [comment]
Awesome thank you 😀
